function params = default_params()
    params.FP = struct('Color', [1 0 0], 'Size', 0.5, 'Threshold', 1.0);
    params.TG = struct('Color', [1 1 1], 'Size', 0.5, 'Threshold', 1.0);
    
    params.RepeatStimulusInvalid = false;
    params.RewardProbability = 1.0;
    
    params.Timing = struct( ...
        'AcquireFP', 1000, ...
        'FPHold', fuzzed_uniform(900, 1100), ...
        'TGOnToFPOff', fuzzed_uniform(900, 1100), ...
        'ResponseWindow', 3000, ...
        'MaximumSaccade', 1000, ...
        'TGHoldToReward', 0, ...
        'InterTrialInterval', fuzzed_uniform(1000, 1000), ...
        'RewardDuration', fuzzed_uniform(100, 100), ...
        'InvalidTimeout', 0 ...
        );
    % params.Block = {struct('LeftBias', 0.5, 'Coherence', 1.0, 'TrialCount', 100)};
    params.Position = struct('Target', [-3 3], 'Center', [0 0]);
    % params.Angle = struct('Left', '135deg', 'Right', '45deg');
end
